# -*- coding: utf-8 -*-
"""danish

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QsrnxPmwIDW7D5fbxKS2rb7lEh1PFoID
"""

import pyautogui

pic= pyautogui.screenshot()

pic.save('screenshot.png')