# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bQtA-VSER4ZyvFl9TBjGIqAyfBft_Jjj
"""

print("khawar Raza")
print("AM")