# -*- coding: utf-8 -*-
"""project.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VPcovdmmpBwoMw5PfwCioZQjEuCKSshZ
"""

print("Name:Shahmeer ")
print("Section:BM")
print("ID:sp19-bsse-0007")