# -*- coding: utf-8 -*-
"""saad.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mn-yuKjWirXXY5bBuJbSj5HtNfGme70T
"""

print("Name : SAad")
print("Section: BM")